name: Publish

on:
  push:
    tags:
      - "v*.*.*" # matches semantic versioning tags like v1.0.0
    branches:
      - main

jobs:
  package_mod:
    runs-on: windows-latest
    env:
      MOD_NAME_CONDENSED: ${{ join(vars.MOD_NAME, '') }}
      RELEASE_ARCHIVE: ./builds/${{ join(vars.MOD_NAME, '_') }}_v${{ github.ref_name }}.7z
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "true"
      - name: Install VS Code Task Runner # https://pypi.org/project/vscode-task-runner/
        run: pipx install "vscode-task-runner==3.1.0"
      - name: Compile Papyrus Scripts
        run: vtr "Compile Papyrus Scripts"
      - name: Create Archives
        run: vtr "Create Archives"
      - name: Generate Release Notes
        run: |
          {
            echo 'CHANGELOG_FULL<<EOF'
            gh pr list --search '${{ github.ref_name }}' --state merged --json body --jq '.[].body'
            echo 'EOF'
          } >>"$GITHUB_ENV"
      - name: Create GitHub Release
        run: >
          gh release create
          ${{ github.ref_name }}
          "${{ env.RELEASE_ARCHIVE }}"
          --notes "${{ env.CHANGELOG_FULL }}"
      - name: Transform Release Notes For Nexus Mods
        run: |
          {
            echo 'CHANGELOG_NEXUS<<EOF'
            "${{ env.CHANGELOG_FULL }}" | Select-Object -Skip 2 | ForEach-Object { $_Substring(2) }
            echo 'EOF'
          } >>"$GITHUB_ENV"
      - name: Upload to Nexus Mods
        uses: Nexus-Mods/upload-action@c96019556046053aa26044b44396cd38929daf23 # v1.0.0-beta.10
        with:
          api_key: ${{ secrets.NEXUS_MODS_API_KEY }}
          file_id: ${{ vars.NEXUS_FILE_ID }}
          filename: ${{ env.RELEASE_ARCHIVE }}
          version: ${{ github.ref_name }}
          display_name: ${{ vars.MOD_NAME }}
          description: See changelog for full details.
          category: main
          archive_existing_version: true
          primary_mod_manager_download: true
          allow_mod_manager_download: true
          show_requirements_pop_up: false
          update_mod_version: true
          mod_id: ${{ vars.NEXUS_MOD_ID }}
          changelog: ${{ env.CHANGELOG_NEXUS }}
