name: Publish

on:
  push:
    tags:
      - "v*.*.*" # matches semantic versioning tags like v1.0.0
    branches:
      - main

jobs:
  package_mod:
    runs-on: windows-latest
    env:
      MOD_NAME_CONDENSED: ${{ join(vars.MOD_NAME, '') }}
      ARCHIVE_NAME: ${{ join(vars.MOD_NAME, '_') }}_v${{ github.ref_name }}.7z
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: "true"
      # compile scripts
      - name: Compile Starvival Scripts
        run: >
          ./support/papyrus-imports/vanilla/bin/PapyrusCompiler/PapyrusCompiler.exe
          "./support/scripts/SVFStarvivalPatch.ppj"
      - name: Compile Main Scripts
        run: >
          ./support/papyrus-imports/vanilla/bin/PapyrusCompiler/PapyrusCompiler.exe
          "./support/scripts/${{ env.MOD_NAME_CONDENSED }}.ppj"
      # create archives
      - name: Create Starvival Patch BA2
        shell: pwsh
        run: >
          ./support/common/scripts/build-archives.ps1
          -DataDir
          "./data-starvival-patch"
          -PluginName
          "SVF-Starvival-Patch"
          -Starfield
          -Skip7z
          -SkipBA2Cleanup
          -BA2ForceUncompressed
          -BA2DisableSharing
      - name: Create Main BA2
        shell: pwsh
        run: >
          ./support/common/scripts/build-archives.ps1
          -ModName
          "${{ vars.MOD_NAME }}"
          -Starfield
          -Skip7z
          -SkipBA2Cleanup
          -BA2ForceUncompressed
          -BA2DisableSharing
      - name: Create Archive
        shell: pwsh
        run: >
          ./support/common/scripts/build-archives.ps1
          -ModName
          "${{ vars.MOD_NAME }}"
          -Starfield
          -SkipBA2
      # upload to nexus mods
      - name: Upload to Nexus Mods
        uses: Nexus-Mods/upload-action@f6e1e2ea683dfe8f88cccf642c6e0e69ab66825e # v1.0.0-beta.8
        with:
          api_key: ${{ secrets.NEXUS_MODS_API_KEY }}
          file_id: ${{ vars.NEXUS_FILE_ID }}
          filename: ./builds/${{ env.ARCHIVE_NAME }}
          version: ${{ github.ref_name }}
          display_name: ${{ vars.MOD_NAME }}
          archive_existing_version: true
          primary_mod_manager_download: true
          description: See changelog for full details.
      # grab the body of the merged PR, which should be the changelog entry
      - name: Generate Release Notes
        run: >
          gh pr list
          --search '${{ github.ref_name }}'
          --state merged
          --json body
          --jq '.[].body'
          > release_notes.txt
      # publish github release
      - name: Create GitHub Release
        run: >
          gh release create
          ${{ github.ref_name }}
          "./builds/${{ env.ARCHIVE_NAME }}"
          --notes-file release_notes.txt
